import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const myFont = localFont({
    variable: "--font-gopher",
    src: [
        { path: "./fonts/Gopher-Thin.ttf", weight: "300" },
        { path: "./fonts/Gopher-Regular.ttf", weight: "400" },
        { path: "./fonts/Gopher-Medium.ttf", weight: "510" },
        { path: "./fonts/Gopher-Bold.ttf", weight: "600" },
    ],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${myFont.variable} antialiased  `}>
                <header className="absolute flex px-[3.75vw] py-[1vw] justify-between items-center z-2 w-full bg-[var(--primary)]">
                    <span className="md:text-[calc((2-1)_*_1.2vw_+_1rem)] text-[calc((1.2-1)*calc(.012*min(100vh,900px))+1rem)] font-[510]">
                        Lilac Template
                    </span>
                    <span className="text-[18px]">
                        <span>Blog</span>
                        <span className="ml-10">Contact</span>
                    </span>
                </header>
                {children}
            </body>
        </html>
    );
}
